{% if theme.use_motion %}

  <script src="http://7xn4vv.com1.z0.glb.clouddn.com/static/lib/velocity/velocity.min.js"></script>
  <script src="http://7xn4vv.com1.z0.glb.clouddn.com/static/lib/velocity/velocity.ui.min.js"></script>

  <script src="http://7xn4vv.com1.z0.glb.clouddn.com/static/js/motion_global.js" id="motion.global"></script>

{% else %}

  <script src="http://7xn4vv.com1.z0.glb.clouddn.com/static/js/motion_fallback.js" id="motion.fallback"></script>

{% endif %}
